export default Object.freeze({
  ACCOUNT: "Account",
  ACCOUNT_EDIT: "AccountEdit",
  ACCOUNT_NAV: "AccountNavigation",
  APARTMENT: "Apartment",
  CHORES: "Chores",
  CHORE_ADD: "ChoreAdd",
  CHORE_EDIT: "ChoreEdit",
  CHORE_NAV: "ChoreNavigation",
  CREATE_SUITE: "CreateSuite",
  JOIN_SUITE: "JoinSuite",
  PAYMENTS: "Payments",
  PAYMENT_ADD: "PaymentAdd",
  PAYMENT_HISTORY: "PaymentHistory",
  PAYMENT_NAV: "PaymentNavigation",
  REGISTER: "Register",
  RULES: "Rules",
  RULES_NAV: "RulesNavigator",
  SUITE: "Suite",
  TESTING_RES: "Testing",
  WELCOME: "Welcome",
});
